# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: [".env"]

tasks:
  default:
    desc: Runs the project in dev mode
    cmds:
      - go run cmd/vivery/main.go

  infra:
    desc: Runs all needed infra
    cmds:
      - docker compose -f docker-compose.infra.yaml up -d

  migrate:
    desc: Runs all migrations
    cmds:
      - tern migrate --migrations migrations
